### PR TITLE
[WIP] [ENH] Improved map2loop - gempy integration

### PR DESCRIPTION
**Pull request by Leguark**
- New loop2gempy_pro function
- New notetook Map2Loop2GemPy minimal example
- New test

### CODE REVIEW

**Comment by markjessell** [comment]
A few questions:

1) What is the functional difference between loop2gempy_pro and loop2gempy?

2) Does the NB 1a. All in one Hamersley-gempy.ipnb need the code starting with the Cell: g = Out[67], as it crashes with a key error. Or should all gempy-related code be replaced by equivalent code from Map2Loop2GemPy- All in one Hamersley.ipnb and remove the old NB?

3) The map view of the model produced by the loop2gempy_pro code looks pretty good, but the surfaces are crazy and have no obvious relationship to the map? The map view is still very noisy though, when compared to the geomodeller map using the same data, this may be difference in the co-kriging parameters used (see comparison images:

geomodeller

geomod

gempy

gempy

, accepting that gempy didn't use the fault data)?

4) The 3D surfaces produced by loop2gempy look OK, except that the domes become basins and the basins become domes relative to the real data, can't tell if this is an issue with loop2gempy_pro?

5. How is the vertical exaggeration (ve) information passed to gempy, I could see how it was being used?   

6. Given all this, should I accept the pull request?

**Comment by Leguark** [comment]
Hey Mark, sorry I did not described the pull request more in detail! I was planning to have finished yesterday but in the end I did not find the motivation. The main reason to do the pull request is for you to follow what I am doing and help me to polish it.

1. I did not compare them in terms of the output. I just rewrote the function using more gempy syntax. In general, this should avoid some objects not updating when other objects get updated. I will try to do some comparison

2. I forgot to update that notebook. We should updated with the new function. I will do it in the next commit.

3. I think the problem is that we have too much vertical anisotropy (I should rename ve to va).  We are multiplying all coordinates by 30 (during the whole interpolation and representation). Also this exaggeration is the reason why the surfaces are so extreme.

In any case, this vertical anistropy at the moment is a dirty patch I did to try to get better results. We are working on cgre-aachen/gempy#266 , cgre-aachen/gempy#341 and cgre-aachen/gempy#265 to integrate anisotropies properly.
The noise on the map I think is due to the extreme vertical anisotropy. I will play with the value

4. I am not sure how to deal with this

5. Again, ve is misleading because it is not only on the plot side but on the whole Z coordinates to do it more isotropic.

6. Nop

**Comment by markjessell** [comment]
Thanks, 

4. Funnily enough LoopStructural had the same problem for point 4 (domes->basins) it was a sign problem with the use of orientations in Lachie's case, I guess the same here?

5. I was more trying to learn how the info in the variable ve was being passed to gempy, since it is not on the parameter list of any of the functions? Is that code just for explanation?

**Comment by Leguark** [comment]
3. Looking to the map in vtk it looks much better - you can get that view by pressing L in the vtk renderer to hide the layers. I think is just because vtk smooth the plot. I really need to fix the plot_map option and then I can try to understand why it looks so noisy.
 
image


4. In GemPy (this is different to geomodeller) we do not use the order of the surfaces (within a group) as constrain, so I think it has to be some rogue data point. Hopefully I can put it in VR soon to try to understand better what is going on because there is clearly quite a few artifacts. I think all related to using one single range and not having anisotropy - perfect case study for us to work in that part of the code

5. At the moment if you look to the loop2gempy_pro I just use ve to multiply a bunch of Z arrays.

6. I think it is as good as it gets right now so maybe we should merge it and we will keep using this model to tune the hyperparameters

**Pull request merged**
