### PR TITLE
Adding fault orientation data

### PR DESCRIPTION
**Pull request by lachlangrose**
Changes existing behaviour by not adding structural data to the fault traces. New changes to LoopStructural will mean the models build fine. 
Adds a new datatype, fault orientations which are a shapefile for the orientation of a fault. 
Adding in a new calculator type which determines which faults an orientation belongs to. Basic nearest fault example is shown but could be extended to use the fault ellipsoid or to prioritise faults whose trace matches the strike of the fault orientation.

### CODE REVIEW

**Review by rabii-chaarani — APPROVED** [review]

**Review by rabii-chaarani — APPROVED** [review]

**Review by rabii-chaarani — APPROVED** [review]

**Comment by RoyThomsonMonash** [comment]
Only a couple of things (I am being quite picky though :D ):
- In fault_orientation.py does compute describe the action of the fault orientation class (for the sorter ABC it's sort and for calculators it's compute)?  In the comments you describe it as assigning or estimating, perhaps that's a better function name.
- There are a couple of places in project.py that commented out code remains. (save_into_projectfile() and summarise_fault_data())

On linting:
- black seems quite aggressive (is your line length set to 88) did we agree to 100?
- We should black all the .py files at once (perhaps in a separate issue and branch) as it makes the commit log easier to read
- flake8 and black seem to disagree with some options (whitespace before ':')

**Review by RoyThomsonMonash — CHANGES_REQUESTED** [review]
Only a couple of things (I am being quite picky though :D ):
- In fault_orientation.py does compute describe the action of the fault orientation class (for the sorter ABC it's sort and for calculators it's compute)? In the comments you describe it as assigning or estimating, perhaps that's a better function name.
- There are a couple of places in project.py that commented out code remains. (save_into_projectfile() and summarise_fault_data())

On linting:
- black seems quite aggressive (is your line length set to 88) did we agree to 100?
- We should black all the .py files at once (perhaps in a separate issue and branch) as it makes the commit log easier to read
- flake8 and black seem to disagree with some options (whitespace before ':')

Summary:
Check linting settings
Happy to use compute in FaultOrientation class but could change
Remove old commented out code

**Review by lachlangrose — COMMENTED** [review]
Thanks @RoyThomsonMonash. I actually wonder whether it would make more sense for the sorters, calculators etc to be `__call__` methods. This would mean you could call them as `self.fault_orientations(arguments)`

I have added lint setting and black settings in #35 

@AngRodrigues do you have any comments before we merge this code into map2loop?

**Review by RoyThomsonMonash — APPROVED** [review]
Requested changes fixed, and using ruff linter works.  Not sure about the mapdata.py:664 split of square parentheses but I can live with it.

**Comment by lachlangrose** [comment]
I hadn't noticed that, but it does mean the diff would be smaller if you add more arguments to the accessor.

**Review by AngRodrigues — APPROVED** [review]

**Pull request merged**
